import { extractYouTubeVideoId, decodeHtmlEntities } from "@/lib/cleanTitle";

export interface YouTubeTranscriptCue {
  text: string;
  startMs: number;
  durationMs: number;
  formattedTime: string;
}

export interface YouTubeTranscriptResult {
  videoId: string;
  title?: string;
  author?: string;
  description?: string;
  languageCode: string;
  languageName?: string;
  isAutoGenerated: boolean;
  cues: YouTubeTranscriptCue[];
  plainText: string;
  markdownWithTimestamps: string;
  durationSec: number;
  wordCount: number;
}

export interface CaptionTrack {
  baseUrl: string;
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
  vssId?: string;
  languageCode?: string;
  kind?: string; // "asr" = auto-generated speech recognition
  isTranslatable?: boolean;
}

export interface TranscriptOptions {
  lang?: string;
  timeoutMs?: number;
}

/**
 * Format milliseconds into MM:SS or HH:MM:SS format.
 */
export function formatTimestamp(ms: number): string {
  const totalSeconds = Math.max(0, Math.floor(ms / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const pad = (n: number) => n.toString().padStart(2, "0");

  if (hours > 0) {
    return `${hours}:${pad(minutes)}:${pad(seconds)}`;
  }
  return `${pad(minutes)}:${pad(seconds)}`;
}

/**
 * Clean subtitle text by decoding HTML entities and stripping any inner XML tags.
 */
export function cleanSubtitleText(raw: string): string {
  if (!raw) return "";
  const noTags = raw.replace(/<[^>]+>/g, " ");
  return decodeHtmlEntities(noTags).replace(/\s+/g, " ").trim();
}

/**
 * Parses YouTube JSON3 timedtext format (preferred modern format).
 */
export function parseJson3Transcript(data: any): YouTubeTranscriptCue[] {
  if (!data || !Array.isArray(data.events)) {
    return [];
  }

  const cues: YouTubeTranscriptCue[] = [];

  for (const ev of data.events) {
    if (!ev.segs || !Array.isArray(ev.segs)) continue;

    const text = ev.segs
      .map((s: any) => s.utf8 || "")
      .join("")
      .trim();

    if (!text || text === "\n") continue;

    const startMs = Number(ev.tStartMs) || 0;
    const durationMs = Number(ev.dDurationMs) || 0;
    const cleanText = cleanSubtitleText(text);

    if (cleanText) {
      cues.push({
        text: cleanText,
        startMs,
        durationMs,
        formattedTime: formatTimestamp(startMs),
      });
    }
  }

  return cues;
}

/**
 * Parses legacy XML / timedtext subtitle format.
 */
export function parseXmlTranscript(xml: string): YouTubeTranscriptCue[] {
  if (!xml || typeof xml !== "string") return [];

  const cues: YouTubeTranscriptCue[] = [];
  const textRegex = /<text\s+([^>]*?)>(.*?)<\/text>/gi;
  let match: RegExpExecArray | null;

  while ((match = textRegex.exec(xml)) !== null) {
    const attrs = match[1] || "";
    const rawText = match[2] || "";

    const startMatch = attrs.match(/start="([\d.]+)"/i);
    const durMatch = attrs.match(/dur="([\d.]+)"/i);

    const startSec = startMatch ? parseFloat(startMatch[1]) : 0;
    const durSec = durMatch ? parseFloat(durMatch[1]) : 0;

    const startMs = Math.round(startSec * 1000);
    const durationMs = Math.round(durSec * 1000);

    const cleanText = cleanSubtitleText(rawText);

    if (cleanText) {
      cues.push({
        text: cleanText,
        startMs,
        durationMs,
        formattedTime: formatTimestamp(startMs),
      });
    }
  }

  return cues;
}

/**
 * Select the best matching caption track for the given language.
 */
export function selectBestCaptionTrack(
  tracks: CaptionTrack[],
  preferredLang = "en"
): CaptionTrack | null {
  if (!tracks || tracks.length === 0) return null;

  const target = preferredLang.toLowerCase();

  // 1. Exact non-auto-generated language match (e.g. "en")
  const exactManual = tracks.find(
    (t) => t.languageCode?.toLowerCase() === target && t.kind !== "asr"
  );
  if (exactManual) return exactManual;

  // 2. Exact auto-generated language match (e.g. "en" with kind "asr")
  const exactAuto = tracks.find((t) => t.languageCode?.toLowerCase() === target);
  if (exactAuto) return exactAuto;

  // 3. Prefix match (e.g. "en-US" matches "en")
  const prefixMatch = tracks.find((t) =>
    t.languageCode?.toLowerCase().startsWith(target)
  );
  if (prefixMatch) return prefixMatch;

  // 4. Default / first English track available
  const englishFallback = tracks.find((t) =>
    t.languageCode?.toLowerCase().includes("en")
  );
  if (englishFallback) return englishFallback;

  // 5. First available track
  return tracks[0] || null;
}

/**
 * Extracts player response JSON from YouTube HTML page by scanning for balanced brackets.
 */
export function extractPlayerResponseFromHtml(html: string): any | null {
  const marker = "ytInitialPlayerResponse";
  let idx = html.indexOf(marker);

  while (idx !== -1) {
    const eqIdx = html.indexOf("=", idx + marker.length);
    if (eqIdx !== -1 && eqIdx - (idx + marker.length) < 30) {
      const openBrace = html.indexOf("{", eqIdx);
      if (openBrace !== -1 && openBrace - eqIdx < 15) {
        let depth = 0;
        let inString: string | null = null;
        let escape = false;

        for (let i = openBrace; i < html.length; i++) {
          const char = html[i];

          if (escape) {
            escape = false;
            continue;
          }

          if (char === "\\") {
            escape = true;
            continue;
          }

          if (inString) {
            if (char === inString) {
              inString = null;
            }
            continue;
          }

          if (char === '"' || char === "'") {
            inString = char;
            continue;
          }

          if (char === "{") {
            depth++;
          } else if (char === "}") {
            depth--;
            if (depth === 0) {
              const jsonStr = html.slice(openBrace, i + 1);
              try {
                return JSON.parse(jsonStr);
              } catch {
                break;
              }
            }
          }
        }
      }
    }
    idx = html.indexOf(marker, idx + marker.length);
  }

  return null;
}

/**
 * Fetch video details and caption tracks via YouTube InnerTube Web/Android API.
 */
async function fetchInnerTubePlayer(
  videoId: string,
  timeoutMs = 6000
): Promise<any | null> {
  const url = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
  const body = {
    context: {
      client: {
        hl: "en",
        gl: "US",
        clientName: "ANDROID",
        clientVersion: "19.09.37",
        androidSdkVersion: 30,
      },
    },
    videoId,
  };

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent":
          "com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip",
      },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(timeoutMs),
    });

    if (res.ok) {
      return await res.json();
    }
  } catch {
    // InnerTube failed
  }

  return null;
}

/**
 * Fetch caption cues from timedtext track URL.
 */
async function fetchCaptionCues(
  baseUrl: string,
  timeoutMs = 6000
): Promise<YouTubeTranscriptCue[]> {
  // Strategy 1: JSON3 timedtext
  try {
    const json3Url = baseUrl.includes("fmt=") ? baseUrl : `${baseUrl}&fmt=json3`;
    const res = await fetch(json3Url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      },
      signal: AbortSignal.timeout(timeoutMs),
    });

    if (res.ok) {
      const text = await res.text();
      if (text && text.trim().length > 0) {
        try {
          const json = JSON.parse(text);
          const cues = parseJson3Transcript(json);
          if (cues.length > 0) return cues;
        } catch {
          // Fall through to XML
        }
      }
    }
  } catch {
    // JSON3 failed
  }

  // Strategy 2: Raw XML timedtext
  try {
    const res = await fetch(baseUrl, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      },
      signal: AbortSignal.timeout(timeoutMs),
    });

    if (res.ok) {
      const xml = await res.text();
      if (xml && xml.trim().length > 0) {
        const cues = parseXmlTranscript(xml);
        if (cues.length > 0) return cues;
      }
    }
  } catch {
    // XML failed
  }

  return [];
}

/**
 * Extract transcripts, subtitles, and captions from a YouTube video URL or ID.
 *
 * Extracts from YouTube timedtext tracks, with resilient metadata fallback.
 */
export async function fetchYouTubeTranscript(
  urlOrId: string,
  options?: TranscriptOptions
): Promise<YouTubeTranscriptResult | null> {
  const videoId =
    urlOrId.length === 11 && !urlOrId.includes("/")
      ? urlOrId
      : extractYouTubeVideoId(urlOrId);

  if (!videoId) return null;

  const timeoutMs = options?.timeoutMs || 8000;
  const preferredLang = options?.lang || "en";

  let playerResponse: any = null;
  let videoTitle: string | undefined;
  let videoAuthor: string | undefined;
  let videoDescription: string | undefined;
  let durationSec = 0;

  // ─── Step 1: Try fetching the YouTube Watch HTML page ───────────────────────
  try {
    const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=${encodeURIComponent(
      preferredLang
    )}`;
    const pageRes = await fetch(watchUrl, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9",
      },
      signal: AbortSignal.timeout(timeoutMs),
    });

    if (pageRes.ok) {
      const html = await pageRes.text();
      playerResponse = extractPlayerResponseFromHtml(html);
    }
  } catch {
    // HTML page fetch failed
  }

  // ─── Step 2: InnerTube Player API fallback ──────────────────────────────────
  if (!playerResponse?.videoDetails) {
    const innerTubeData = await fetchInnerTubePlayer(videoId, timeoutMs);
    if (innerTubeData) {
      playerResponse = innerTubeData;
    }
  }

  // ─── Step 3: oEmbed fallback for metadata if needed ─────────────────────────
  if (!playerResponse?.videoDetails) {
    try {
      const oembedRes = await fetch(
        `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`,
        { signal: AbortSignal.timeout(4000) }
      );
      if (oembedRes.ok) {
        const oembed = await oembedRes.json();
        videoTitle = oembed.title;
        videoAuthor = oembed.author_name;
      }
    } catch {
      // oembed failed
    }
  } else {
    videoTitle =
      playerResponse?.videoDetails?.title ||
      playerResponse?.microformat?.playerMicroformatRenderer?.title?.simpleText;
    videoAuthor =
      playerResponse?.videoDetails?.author ||
      playerResponse?.microformat?.playerMicroformatRenderer?.ownerChannelName;
    videoDescription = playerResponse?.videoDetails?.shortDescription;
    const len = Number(playerResponse?.videoDetails?.lengthSeconds);
    if (!isNaN(len) && len > 0) durationSec = len;
  }

  const captionTracks: CaptionTrack[] =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];

  let cues: YouTubeTranscriptCue[] = [];
  let isAutoGenerated = false;
  let languageCode = "en";
  let languageName = "English";

  if (captionTracks && captionTracks.length > 0) {
    const selectedTrack = selectBestCaptionTrack(captionTracks, preferredLang);
    if (selectedTrack && selectedTrack.baseUrl) {
      languageCode = selectedTrack.languageCode || "en";
      isAutoGenerated = selectedTrack.kind === "asr";
      languageName =
        selectedTrack.name?.simpleText ||
        selectedTrack.name?.runs?.[0]?.text ||
        selectedTrack.languageCode ||
        "English";

      cues = await fetchCaptionCues(selectedTrack.baseUrl, timeoutMs);
    }
  }

  // Calculate plain text and formatted markdown with timestamps
  const plainText = cues.map((c) => c.text).join(" ");
  const markdownWithTimestamps = cues
    .map((c) => `[${c.formattedTime}] ${c.text}`)
    .join("\n");

  if (cues.length > 0) {
    const lastCue = cues[cues.length - 1];
    durationSec = Math.max(
      durationSec,
      Math.ceil((lastCue.startMs + lastCue.durationMs) / 1000)
    );
  }

  const words = plainText.split(/\s+/).filter(Boolean);

  return {
    videoId,
    title: videoTitle,
    author: videoAuthor,
    description: videoDescription,
    languageCode,
    languageName,
    isAutoGenerated,
    cues,
    plainText,
    markdownWithTimestamps,
    durationSec: durationSec || 300,
    wordCount: words.length,
  };
}
