"use client";

import React, { useState, useMemo } from "react";
import {
  FinancialAuditRow,
  FinancialAuditAnalysis,
  AuditSubscriptionCull,
  AuditTacticalAction,
} from "@/lib/ledger/types";
import { formatCurrency, formatSignedCurrency, getCurrencySymbol } from "@/lib/ledger/formatters";
import { playSound } from "@/lib/sound";
import { AuditTrajectoryChart } from "./charts/AuditTrajectoryChart";
import { LedgerErrorBoundary } from "./LedgerErrorBoundary";
import {
  Sparkles,
  TrendingUp,
  Scissors,
  Target,
  CheckCircle2,
  ListChecks,
  Copy,
  Check,
  RotateCcw,
  ShieldCheck,
  ShieldAlert,
  Coins,
  ArrowRight,
  Flame,
  PieChart,
  MessageSquareQuote,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

interface LedgerAuditModalProps {
  isOpen: boolean;
  onClose: () => void;
  latestAudit: FinancialAuditRow | null;
  onAuditGenerated: (audit: FinancialAuditRow) => void;
}

type AuditTab = "OVERVIEW" | "TRAJECTORY" | "CULLS" | "DEBT_SIP" | "CHECKLIST";

export const LedgerAuditModal: React.FC<LedgerAuditModalProps> = ({
  isOpen,
  onClose,
  latestAudit,
  onAuditGenerated,
}) => {
  const [activeTab, setActiveTab] = useState<AuditTab>("OVERVIEW");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedBrief, setCopiedBrief] = useState(false);
  const [expandedScriptIndex, setExpandedScriptIndex] = useState<number | null>(null);
  const [completedTaskIds, setCompletedTaskIds] = useState<Record<string, boolean>>({});

  const analysis = latestAudit?.analysis as unknown as FinancialAuditAnalysis | undefined;
  const currency = analysis?.currency || "USD";
  const sym = getCurrencySymbol(currency);

  const totalAnnualCullSavings = useMemo(() => {
    if (!analysis?.subscriptionCullList || !Array.isArray(analysis.subscriptionCullList)) return 0;
    return analysis.subscriptionCullList.reduce((acc, c) => acc + (Number(c?.annualSavings) || 0), 0);
  }, [analysis]);

  const handleRunAudit = async () => {
    try {
      setLoading(true);
      setError(null);
      playSound.click();

      const res = await fetch("/api/financial/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to generate financial audit");
      }

      const data = await res.json();
      onAuditGenerated(data.audit);
      playSound.fileIt();
      setActiveTab("OVERVIEW");
    } catch (err: any) {
      setError(err.message || "Failed to synthesize audit");
    } finally {
      setLoading(false);
    }
  };

  const handleCopyExecutiveBrief = () => {
    if (!analysis) return;
    playSound.click();

    const cullSavings = Array.isArray(analysis.subscriptionCullList)
      ? analysis.subscriptionCullList.reduce((s, c) => s + (Number(c?.annualSavings) || 0), 0)
      : 0;

    const brief = `
# 🏛️ THE HOARD INSTITUTIONAL FINANCIAL AUDIT
Date: ${latestAudit?.createdAt ? new Date(latestAudit.createdAt).toLocaleDateString() : new Date().toLocaleDateString()}
Overall Health Score: ${analysis.healthScore ?? 75}/100

## 🎯 Executive Verdict
${analysis.summaryVerdict || "Financial velocity analyzed."}

## 📊 4-Pillar Scorecard
- Emergency Runway: ${analysis.pillars?.runway?.score ?? analysis.runwayAnalysis?.currentRunwayMonths ?? "N/A"}/100 [${analysis.pillars?.runway?.status ?? analysis.runwayAnalysis?.safetyEvaluation ?? "STABLE"}]
- Debt Control: ${analysis.pillars?.debt?.score ?? "N/A"}/100 [${analysis.pillars?.debt?.status ?? "N/A"}]
- Fixed Burn Efficiency: ${analysis.pillars?.burn?.score ?? "N/A"}/100 [${analysis.pillars?.burn?.status ?? "N/A"}]
- Wealth Velocity & SIPs: ${analysis.pillars?.wealth?.score ?? "N/A"}/100 [${analysis.pillars?.wealth?.status ?? "N/A"}]

## ✂️ Subscription Cull Targets (Potential Savings: ${sym}${cullSavings.toLocaleString()}/yr)
${Array.isArray(analysis.subscriptionCullList) ? analysis.subscriptionCullList.map((c) => `- ${c.name}: +${sym}${c.annualSavings}/yr savings (${c.reason})`).join("\n") : "None"}

## 🎯 Debt Knockout Strategy (${analysis.debtAccelerationStrategy?.recommendedStrategy || "AVALANCHE"})
- Priority Debt Target: ${analysis.debtAccelerationStrategy?.targetPriorityDebt || "Primary debt"}
- Extra Payment Recommendation: +${sym}${analysis.debtAccelerationStrategy?.extraPaymentRecommendation ?? 100}/mo
- Projected Interest Savings: ${sym}${(analysis.debtAccelerationStrategy?.projectedInterestSavings ?? 0).toLocaleString()}

Generated by Gemini 3.5 Pro Financial Scribe.
    `.trim();

    navigator.clipboard.writeText(brief);
    setCopiedBrief(true);
    setTimeout(() => setCopiedBrief(false), 2000);
  };

  const toggleTask = (taskId: string) => {
    playSound.click();
    setCompletedTaskIds((prev) => ({ ...prev, [taskId]: !prev[taskId] }));
  };

  if (!isOpen) return null;

  // Score color calculation helper
  const getScoreColor = (score: number) => {
    if (score >= 80) return "#16A34A";
    if (score >= 60) return "#CA8A04";
    if (score >= 40) return "#EA580C";
    return "#DC2626";
  };

  return (
    <div className="ledger-modal-overlay" onClick={onClose}>
      <div
        className="ledger-modal-box"
        style={{
          maxWidth: "880px",
          width: "95vw",
          maxHeight: "90vh",
          display: "flex",
          flexDirection: "column",
          padding: "0",
          overflow: "hidden",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* ── HEADER ── */}
        <div
          className="ledger-modal-header"
          style={{
            padding: "16px 22px",
            background: "#0A0A0A",
            color: "#FFFFFF",
            borderBottom: "2px solid #000000",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "10px", flexWrap: "wrap" }}>
            <Sparkles size={20} color="#FFE600" aria-hidden="true" />
            <h2 style={{ color: "#FFFFFF", margin: 0, fontSize: "17px", letterSpacing: "0.04em" }}>
              AI FINANCIAL SCRIBE &amp; INSTITUTIONAL AUDITOR
            </h2>
            <span
              style={{
                fontFamily: "var(--mono)",
                fontSize: "10px",
                fontWeight: 900,
                background: "#FFE600",
                color: "#0A0A0A",
                padding: "2px 6px",
                borderRadius: "2px",
              }}
            >
              GEMINI 3.5 QUANT
            </span>
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
            {analysis && (
              <button
                type="button"
                className="btn-card-action"
                onClick={handleCopyExecutiveBrief}
                style={{
                  background: copiedBrief ? "#16A34A" : "#222222",
                  color: "#FFFFFF",
                  borderColor: "#444444",
                  fontSize: "10.5px",
                  display: "flex",
                  alignItems: "center",
                  gap: "4px",
                }}
                title="Copy markdown executive brief"
              >
                {copiedBrief ? <Check size={12} /> : <Copy size={12} />}
                {copiedBrief ? "COPIED" : "EXPORT BRIEF"}
              </button>
            )}

            <button
              type="button"
              className="btn-card-action"
              onClick={onClose}
              style={{
                background: "#222222",
                color: "#FFFFFF",
                borderColor: "#444444",
                padding: "4px 8px",
              }}
              aria-label="Close modal"
            >
              ✕
            </button>
          </div>
        </div>

        {/* ── MODAL BODY SCROLLABLE WRAPPER ── */}
        <div style={{ overflowY: "auto", flex: 1, padding: "20px 22px" }}>
          {error && (
            <div
              style={{
                background: "#FEE2E2",
                color: "#DC2626",
                padding: "10px 14px",
                fontFamily: "var(--mono)",
                fontSize: "11px",
                fontWeight: 700,
                marginBottom: "16px",
                border: "1.5px solid #DC2626",
                borderRadius: "3px",
              }}
            >
              ⚠️ {error}
            </div>
          )}

          {/* ── EMPTY / FIRST TIME TEASER ── */}
          {!analysis && !loading ? (
            <div style={{ textAlign: "center", padding: "36px 16px" }}>
              <div style={{ fontSize: "44px", marginBottom: "12px" }}>🏛️</div>
              <h3
                style={{
                  fontFamily: "var(--display)",
                  fontSize: "24px",
                  fontWeight: 900,
                  marginBottom: "8px",
                }}
              >
                SYNTHESIZE COMPREHENSIVE FINANCIAL AUDIT
              </h3>
              <p
                style={{
                  fontFamily: "var(--mono)",
                  fontSize: "12px",
                  color: "#555555",
                  margin: "0 auto 24px auto",
                  maxWidth: "560px",
                  lineHeight: 1.6,
                }}
              >
                Let Gemini conduct an uncompromising quantitative audit of your entire ledger:
                itemized recurring subscriptions, high-APR debt leverage, emergency liquidity runway,
                and systematic wealth compounding via Gold &amp; Equity SIPs.
              </p>

              {/* 3 Value Proposition Pillars Preview */}
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
                  gap: "12px",
                  maxWidth: "680px",
                  margin: "0 auto 28px auto",
                  textAlign: "left",
                }}
              >
                <div
                  style={{
                    background: "#F8FAFC",
                    border: "1.5px solid #0A0A0A",
                    boxShadow: "2.5px 2.5px 0 #0A0A0A",
                    padding: "12px 14px",
                    borderRadius: "3px",
                  }}
                >
                  <div
                    style={{
                      fontFamily: "var(--mono)",
                      fontSize: "10px",
                      fontWeight: 900,
                      color: "#DC2626",
                      marginBottom: "3px",
                    }}
                  >
                    ✂️ SUBSCRIPTION CULLS
                  </div>
                  <div style={{ fontFamily: "var(--sans)", fontSize: "12px", color: "#333333" }}>
                    Identify hidden recurring leaks with custom retention negotiation scripts.
                  </div>
                </div>

                <div
                  style={{
                    background: "#F8FAFC",
                    border: "1.5px solid #0A0A0A",
                    boxShadow: "2.5px 2.5px 0 #0A0A0A",
                    padding: "12px 14px",
                    borderRadius: "3px",
                  }}
                >
                  <div
                    style={{
                      fontFamily: "var(--mono)",
                      fontSize: "10px",
                      fontWeight: 900,
                      color: "#16A34A",
                      marginBottom: "3px",
                    }}
                  >
                    🎯 DEBT FREEDOM ROUTE
                  </div>
                  <div style={{ fontFamily: "var(--sans)", fontSize: "12px", color: "#333333" }}>
                    Mathematically proven Avalanche vs Snowball prioritization to eliminate predatory interest.
                  </div>
                </div>

                <div
                  style={{
                    background: "#F8FAFC",
                    border: "1.5px solid #0A0A0A",
                    boxShadow: "2.5px 2.5px 0 #0A0A0A",
                    padding: "12px 14px",
                    borderRadius: "3px",
                  }}
                >
                  <div
                    style={{
                      fontFamily: "var(--mono)",
                      fontSize: "10px",
                      fontWeight: 900,
                      color: "#0284C7",
                      marginBottom: "3px",
                    }}
                  >
                    📈 10-YR WEALTH MODEL
                  </div>
                  <div style={{ fontFamily: "var(--sans)", fontSize: "12px", color: "#333333" }}>
                    Simulate compound trajectory gains by deploying freed cash flow into SIPs.
                  </div>
                </div>
              </div>

              <button
                type="button"
                disabled={loading}
                className="btn-ledger btn-ledger-ai"
                onClick={handleRunAudit}
                style={{ fontSize: "13px", padding: "12px 28px", boxShadow: "4px 4px 0 #000000" }}
              >
                <Sparkles size={15} aria-hidden="true" />
                RUN COMPLETE FINANCIAL AUDIT NOW
              </button>
            </div>
          ) : loading ? (
            /* ── LOADING ANIMATION STATE ── */
            <div style={{ textAlign: "center", padding: "60px 20px" }}>
              <div
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                  width: "60px",
                  height: "60px",
                  borderRadius: "50%",
                  background: "#0A0A0A",
                  color: "#FFE600",
                  marginBottom: "16px",
                  border: "2.5px solid #000000",
                  boxShadow: "4px 4px 0 #000000",
                }}
              >
                <Sparkles size={28} className="animate-spin" />
              </div>
              <h3
                style={{
                  fontFamily: "var(--display)",
                  fontSize: "20px",
                  fontWeight: 900,
                  marginBottom: "6px",
                }}
              >
                SYNTHESIZING INSTITUTIONAL AUDIT...
              </h3>
              <p
                style={{
                  fontFamily: "var(--mono)",
                  fontSize: "12px",
                  color: "#666666",
                  maxWidth: "420px",
                  margin: "0 auto",
                }}
              >
                Evaluating recurring subscription drain, calculating predatory APR traps, and
                computing 10-year compounding trajectory models.
              </p>
            </div>
          ) : analysis ? (
            /* ── ACTIVE AUDIT VIEW ── */
            <LedgerErrorBoundary fallbackTitle="AUDIT REPORT RE-SYNTHESIS" onReset={handleRunAudit}>
            <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
              {/* ── TAB BAR ── */}
              <div
                className="sub-filter-group"
                style={{
                  display: "flex",
                  gap: "6px",
                  overflowX: "auto",
                  paddingBottom: "4px",
                  borderBottom: "2px solid #0A0A0A",
                }}
              >
                <button
                  type="button"
                  className={`sub-filter-btn ${activeTab === "OVERVIEW" ? "active" : ""}`}
                  onClick={() => {
                    playSound.click();
                    setActiveTab("OVERVIEW");
                  }}
                >
                  <ShieldCheck size={12} aria-hidden="true" />
                  OVERVIEW &amp; SCORE
                </button>

                <button
                  type="button"
                  className={`sub-filter-btn ${activeTab === "TRAJECTORY" ? "active" : ""}`}
                  onClick={() => {
                    playSound.click();
                    setActiveTab("TRAJECTORY");
                  }}
                >
                  <TrendingUp size={12} aria-hidden="true" />
                  10-YR WEALTH TRAJECTORY
                </button>

                <button
                  type="button"
                  className={`sub-filter-btn ${activeTab === "CULLS" ? "active" : ""}`}
                  onClick={() => {
                    playSound.click();
                    setActiveTab("CULLS");
                  }}
                >
                  <Scissors size={12} aria-hidden="true" />
                  SUBSCRIPTION CULLS ({analysis.subscriptionCullList?.length || 0})
                </button>

                <button
                  type="button"
                  className={`sub-filter-btn ${activeTab === "DEBT_SIP" ? "active" : ""}`}
                  onClick={() => {
                    playSound.click();
                    setActiveTab("DEBT_SIP");
                  }}
                >
                  <Target size={12} aria-hidden="true" />
                  DEBT KNOCKOUT &amp; SIPs
                </button>

                <button
                  type="button"
                  className={`sub-filter-btn ${activeTab === "CHECKLIST" ? "active" : ""}`}
                  onClick={() => {
                    playSound.click();
                    setActiveTab("CHECKLIST");
                  }}
                >
                  <ListChecks size={12} aria-hidden="true" />
                  ACTION CHECKLIST ({analysis.tacticalPlan?.length || analysis.cashFlowOptimization?.length || 0})
                </button>
              </div>

              {/* ────────────────────────────────────────────────────────── */}
              {/* TAB 1: OVERVIEW & FREEDOM SCORE */}
              {/* ────────────────────────────────────────────────────────── */}
              {activeTab === "OVERVIEW" && (
                <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
                  {/* Hero Scorecard & Executive Verdict */}
                  <div
                    style={{
                      background: "#FFFFFF",
                      border: "2.5px solid var(--ink, #0A0A0A)",
                      boxShadow: "4px 4px 0 var(--ink, #0A0A0A)",
                      padding: "20px",
                      borderRadius: "4px",
                      display: "flex",
                      gap: "20px",
                      alignItems: "center",
                      flexWrap: "wrap",
                    }}
                  >
                    {/* Dial */}
                    <div
                      style={{
                        width: "84px",
                        height: "84px",
                        borderRadius: "50%",
                        background: "#0A0A0A",
                        border: "3px solid #0A0A0A",
                        boxShadow: "3px 3px 0 rgba(0,0,0,0.2)",
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        justifyContent: "center",
                        flexShrink: 0,
                        color: "#FFE600",
                      }}
                    >
                      <span
                        style={{
                          fontFamily: "var(--display)",
                          fontSize: "32px",
                          fontWeight: 900,
                          lineHeight: 1,
                        }}
                      >
                        {analysis.healthScore}
                      </span>
                      <span
                        style={{
                          fontFamily: "var(--mono)",
                          fontSize: "8.5px",
                          fontWeight: 900,
                          color: "#A3A3A3",
                          textTransform: "uppercase",
                        }}
                      >
                        HEALTH SCORE
                      </span>
                    </div>

                    {/* Verdict description */}
                    <div style={{ flex: 1, minWidth: "260px" }}>
                      <div
                        style={{
                          fontFamily: "var(--mono)",
                          fontSize: "10.5px",
                          fontWeight: 900,
                          color: "#666666",
                          textTransform: "uppercase",
                          letterSpacing: "0.06em",
                          marginBottom: "4px",
                          display: "flex",
                          alignItems: "center",
                          gap: "5px",
                        }}
                      >
                        <ShieldCheck size={13} color="#16A34A" aria-hidden="true" />
                        EXECUTIVE VERDICT &amp; VELOCITY SUMMARY
                      </div>
                      <div
                        style={{
                          fontFamily: "var(--sans)",
                          fontSize: "14px",
                          fontWeight: 600,
                          color: "var(--ink, #0A0A0A)",
                          lineHeight: 1.45,
                        }}
                      >
                        {analysis.summaryVerdict}
                      </div>
                    </div>
                  </div>

                  {/* 4-Pillar Scorecard Grid */}
                  <div>
                    <div
                      style={{
                        fontFamily: "var(--mono)",
                        fontSize: "11px",
                        fontWeight: 900,
                        textTransform: "uppercase",
                        letterSpacing: "0.06em",
                        color: "#444444",
                        marginBottom: "10px",
                        display: "flex",
                        alignItems: "center",
                        gap: "6px",
                      }}
                    >
                      <PieChart size={13} aria-hidden="true" />
                      4-PILLAR FISCAL HEALTH BREAKDOWN
                    </div>

                    <div
                      style={{
                        display: "grid",
                        gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
                        gap: "12px",
                      }}
                    >
                      {/* Pillar 1: Runway */}
                      <div
                        style={{
                          background: "#F8FAFC",
                          border: "1.5px solid #0A0A0A",
                          boxShadow: "2.5px 2.5px 0 #0A0A0A",
                          padding: "14px",
                          borderRadius: "3px",
                        }}
                      >
                        <div
                          style={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                            marginBottom: "6px",
                          }}
                        >
                          <span style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 900 }}>
                            🛡️ LIQUID RUNWAY
                          </span>
                          <span
                            style={{
                              fontFamily: "var(--display)",
                              fontSize: "16px",
                              fontWeight: 900,
                              color: getScoreColor(analysis.pillars?.runway?.score ?? 70),
                            }}
                          >
                            {analysis.pillars?.runway?.grade ||
                              (analysis.runwayAnalysis?.currentRunwayMonths >= 6 ? "A" : "B")}
                          </span>
                        </div>
                        <div
                          style={{
                            width: "100%",
                            height: "6px",
                            background: "#E2E8F0",
                            borderRadius: "3px",
                            overflow: "hidden",
                            marginBottom: "8px",
                          }}
                        >
                          <div
                            style={{
                              width: `${analysis.pillars?.runway?.score ?? Math.min(100, (analysis.runwayAnalysis?.currentRunwayMonths || 3) * 16)}%`,
                              height: "100%",
                              background: getScoreColor(analysis.pillars?.runway?.score ?? 70),
                            }}
                          />
                        </div>
                        <div style={{ fontFamily: "var(--mono)", fontSize: "10.5px", color: "#555555", lineHeight: 1.35 }}>
                          {analysis.pillars?.runway?.verdict ||
                            `Runway: ${analysis.runwayAnalysis?.currentRunwayMonths?.toFixed(1) || 0} months (${analysis.runwayAnalysis?.safetyEvaluation || "STABLE"}). Target reserve: ${formatCurrency(analysis.runwayAnalysis?.targetEmergencyFund, 0, currency)}.`}
                        </div>
                      </div>

                      {/* Pillar 2: Debt Leverage */}
                      <div
                        style={{
                          background: "#F8FAFC",
                          border: "1.5px solid #0A0A0A",
                          boxShadow: "2.5px 2.5px 0 #0A0A0A",
                          padding: "14px",
                          borderRadius: "3px",
                        }}
                      >
                        <div
                          style={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                            marginBottom: "6px",
                          }}
                        >
                          <span style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 900 }}>
                            ⚡ DEBT CONTROL
                          </span>
                          <span
                            style={{
                              fontFamily: "var(--display)",
                              fontSize: "16px",
                              fontWeight: 900,
                              color: getScoreColor(analysis.pillars?.debt?.score ?? 65),
                            }}
                          >
                            {analysis.pillars?.debt?.grade || "B"}
                          </span>
                        </div>
                        <div
                          style={{
                            width: "100%",
                            height: "6px",
                            background: "#E2E8F0",
                            borderRadius: "3px",
                            overflow: "hidden",
                            marginBottom: "8px",
                          }}
                        >
                          <div
                            style={{
                              width: `${analysis.pillars?.debt?.score ?? 65}%`,
                              height: "100%",
                              background: getScoreColor(analysis.pillars?.debt?.score ?? 65),
                            }}
                          />
                        </div>
                        <div style={{ fontFamily: "var(--mono)", fontSize: "10.5px", color: "#555555", lineHeight: 1.35 }}>
                          {analysis.pillars?.debt?.verdict ||
                            `Strategy: ${analysis.debtAccelerationStrategy?.recommendedStrategy}. Extra +${formatCurrency(analysis.debtAccelerationStrategy?.extraPaymentRecommendation, 0, currency)}/mo saves ${formatCurrency(analysis.debtAccelerationStrategy?.projectedInterestSavings, 0, currency)}.`}
                        </div>
                      </div>

                      {/* Pillar 3: Burn Efficiency */}
                      <div
                        style={{
                          background: "#F8FAFC",
                          border: "1.5px solid #0A0A0A",
                          boxShadow: "2.5px 2.5px 0 #0A0A0A",
                          padding: "14px",
                          borderRadius: "3px",
                        }}
                      >
                        <div
                          style={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                            marginBottom: "6px",
                          }}
                        >
                          <span style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 900 }}>
                            ✂️ BURN DISCIPLINE
                          </span>
                          <span
                            style={{
                              fontFamily: "var(--display)",
                              fontSize: "16px",
                              fontWeight: 900,
                              color: getScoreColor(analysis.pillars?.burn?.score ?? 75),
                            }}
                          >
                            {analysis.pillars?.burn?.grade || "B+"}
                          </span>
                        </div>
                        <div
                          style={{
                            width: "100%",
                            height: "6px",
                            background: "#E2E8F0",
                            borderRadius: "3px",
                            overflow: "hidden",
                            marginBottom: "8px",
                          }}
                        >
                          <div
                            style={{
                              width: `${analysis.pillars?.burn?.score ?? 75}%`,
                              height: "100%",
                              background: getScoreColor(analysis.pillars?.burn?.score ?? 75),
                            }}
                          />
                        </div>
                        <div style={{ fontFamily: "var(--mono)", fontSize: "10.5px", color: "#555555", lineHeight: 1.35 }}>
                          {analysis.pillars?.burn?.verdict ||
                            `${analysis.subscriptionCullList?.length || 0} subscriptions can be culled to save +${formatCurrency(totalAnnualCullSavings, 0, currency)}/year.`}
                        </div>
                      </div>

                      {/* Pillar 4: Wealth Velocity */}
                      <div
                        style={{
                          background: "#F8FAFC",
                          border: "1.5px solid #0A0A0A",
                          boxShadow: "2.5px 2.5px 0 #0A0A0A",
                          padding: "14px",
                          borderRadius: "3px",
                        }}
                      >
                        <div
                          style={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                            marginBottom: "6px",
                          }}
                        >
                          <span style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 900 }}>
                            📈 WEALTH VELOCITY
                          </span>
                          <span
                            style={{
                              fontFamily: "var(--display)",
                              fontSize: "16px",
                              fontWeight: 900,
                              color: getScoreColor(analysis.pillars?.wealth?.score ?? 80),
                            }}
                          >
                            {analysis.pillars?.wealth?.grade || "A"}
                          </span>
                        </div>
                        <div
                          style={{
                            width: "100%",
                            height: "6px",
                            background: "#E2E8F0",
                            borderRadius: "3px",
                            overflow: "hidden",
                            marginBottom: "8px",
                          }}
                        >
                          <div
                            style={{
                              width: `${analysis.pillars?.wealth?.score ?? 80}%`,
                              height: "100%",
                              background: getScoreColor(analysis.pillars?.wealth?.score ?? 80),
                            }}
                          />
                        </div>
                        <div style={{ fontFamily: "var(--mono)", fontSize: "10.5px", color: "#555555", lineHeight: 1.35 }}>
                          {analysis.pillars?.wealth?.verdict ||
                            `10-year compounding impact unlocks +${formatCurrency(analysis.investmentStrategy?.tenYearCompoundingImpact || 25000, 0, currency)} in net worth.`}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Mini Highlights Row */}
                  <div
                    style={{
                      display: "grid",
                      gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
                      gap: "12px",
                    }}
                  >
                    <div
                      style={{
                        background: "#FFF1F2",
                        border: "1.5px solid #E11D48",
                        padding: "12px 14px",
                        borderRadius: "3px",
                      }}
                    >
                      <div style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 900, color: "#9F1239" }}>
                        POTENTIAL CULL SAVINGS
                      </div>
                      <div style={{ fontFamily: "var(--display)", fontSize: "22px", fontWeight: 900, color: "#E11D48" }}>
                        +{formatCurrency(totalAnnualCullSavings, 0, currency)}/yr
                      </div>
                      <div style={{ fontFamily: "var(--mono)", fontSize: "10px", color: "#881337", marginTop: "2px" }}>
                        Across {analysis.subscriptionCullList?.length || 0} recurring subscriptions
                      </div>
                    </div>

                    <div
                      style={{
                        background: "#F0FDF4",
                        border: "1.5px solid #16A34A",
                        padding: "12px 14px",
                        borderRadius: "3px",
                      }}
                    >
                      <div style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 900, color: "#166534" }}>
                        DEBT INTEREST SAVINGS
                      </div>
                      <div style={{ fontFamily: "var(--display)", fontSize: "22px", fontWeight: 900, color: "#16A34A" }}>
                        +{formatCurrency(analysis.debtAccelerationStrategy?.projectedInterestSavings || 0, 0, currency)}
                      </div>
                      <div style={{ fontFamily: "var(--mono)", fontSize: "10px", color: "#14532D", marginTop: "2px" }}>
                        Via {analysis.debtAccelerationStrategy?.recommendedStrategy} route
                      </div>
                    </div>

                    <div
                      style={{
                        background: "#FEFCE8",
                        border: "1.5px solid #CA8A04",
                        padding: "12px 14px",
                        borderRadius: "3px",
                      }}
                    >
                      <div style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 900, color: "#854D0E" }}>
                        10-YR COMPOUNDING BOOST
                      </div>
                      <div style={{ fontFamily: "var(--display)", fontSize: "22px", fontWeight: 900, color: "#A16207" }}>
                        +{formatCurrency(analysis.projections?.[analysis.projections.length - 1]?.deltaGain || analysis.investmentStrategy?.tenYearCompoundingImpact || 0, 0, currency)}
                      </div>
                      <div style={{ fontFamily: "var(--mono)", fontSize: "10px", color: "#713F12", marginTop: "2px" }}>
                        With freed cash flow reinvested
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* ────────────────────────────────────────────────────────── */}
              {/* TAB 2: 10-YEAR WEALTH TRAJECTORY */}
              {/* ────────────────────────────────────────────────────────── */}
              {activeTab === "TRAJECTORY" && (
                <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
                  {analysis.projections && analysis.projections.length > 0 ? (
                    <AuditTrajectoryChart
                      projections={analysis.projections}
                      currency={currency}
                    />
                  ) : (
                    <div
                      style={{
                        background: "#F8FAFC",
                        border: "2px dashed #0A0A0A",
                        padding: "30px",
                        textAlign: "center",
                        borderRadius: "4px",
                      }}
                    >
                      <TrendingUp size={32} style={{ margin: "0 auto 8px auto", color: "#16A34A" }} />
                      <div style={{ fontFamily: "var(--display)", fontSize: "18px", fontWeight: 900 }}>
                        No Trajectory Projections on Previous Audit
                      </div>
                      <p style={{ fontFamily: "var(--mono)", fontSize: "11.5px", color: "#666666", maxWidth: "420px", margin: "6px auto 16px auto" }}>
                        Re-run the audit with the updated Gemini 3.5 engine to compute 1, 3, 5, and 10-year comparative wealth models.
                      </p>
                      <button
                        type="button"
                        className="btn-ledger btn-ledger-ai"
                        onClick={handleRunAudit}
                        disabled={loading}
                      >
                        ✨ RE-RUN AUDIT NOW
                      </button>
                    </div>
                  )}

                  {/* Asset Allocation & Rebalancing Insights (if available) */}
                  {analysis.assetAllocation && (
                    <div
                      style={{
                        background: "var(--card, #FFFFFF)",
                        border: "2px solid var(--ink, #0A0A0A)",
                        boxShadow: "3px 3px 0 var(--ink, #0A0A0A)",
                        padding: "18px 20px",
                        borderRadius: "3px",
                      }}
                    >
                      <div
                        style={{
                          fontFamily: "var(--mono)",
                          fontSize: "11px",
                          fontWeight: 900,
                          color: "#0A0A0A",
                          textTransform: "uppercase",
                          marginBottom: "8px",
                          display: "flex",
                          alignItems: "center",
                          gap: "6px",
                        }}
                      >
                        <PieChart size={13} aria-hidden="true" />
                        PORTFOLIO ASSET ALLOCATION &amp; REBALANCING ADVICE
                      </div>
                      <p style={{ fontFamily: "var(--sans)", fontSize: "13px", color: "#333333", lineHeight: 1.45, margin: "0 0 12px 0" }}>
                        {analysis.assetAllocation.rebalanceAdvice}
                      </p>

                      {/* Side by side comparison */}
                      <div
                        style={{
                          display: "grid",
                          gridTemplateColumns: "1fr 1fr",
                          gap: "12px",
                          fontFamily: "var(--mono)",
                          fontSize: "10.5px",
                        }}
                      >
                        <div style={{ background: "#F1F5F9", padding: "10px 12px", borderRadius: "2px" }}>
                          <b style={{ color: "#475569" }}>CURRENT ALLOCATION:</b>
                          <div style={{ marginTop: "4px", display: "flex", flexDirection: "column", gap: "2px" }}>
                            <span>Liquid Cash: {analysis.assetAllocation.current?.liquidCashPct ?? 10}%</span>
                            <span>Equities / Mutual Funds: {analysis.assetAllocation.current?.equitiesAndMutualFundsPct ?? 30}%</span>
                            <span>Precious Metals / Gold: {analysis.assetAllocation.current?.preciousMetalsPct ?? 10}%</span>
                            <span>Crypto / Real Estate: {(analysis.assetAllocation.current?.cryptoPct ?? 5) + (analysis.assetAllocation.current?.realEstatePct ?? 0)}%</span>
                          </div>
                        </div>

                        <div style={{ background: "#DCFCE7", border: "1px solid #16A34A", padding: "10px 12px", borderRadius: "2px" }}>
                          <b style={{ color: "#166534" }}>RECOMMENDED ALLOCATION:</b>
                          <div style={{ marginTop: "4px", display: "flex", flexDirection: "column", gap: "2px", color: "#14532D" }}>
                            <span>Liquid Cash: {analysis.assetAllocation.recommended?.liquidCashPct ?? 15}%</span>
                            <span>Equities / Mutual Funds: {analysis.assetAllocation.recommended?.equitiesAndMutualFundsPct ?? 45}%</span>
                            <span>Precious Metals / Gold: {analysis.assetAllocation.recommended?.preciousMetalsPct ?? 10}%</span>
                            <span>Crypto / Real Estate: {(analysis.assetAllocation.recommended?.cryptoPct ?? 5) + (analysis.assetAllocation.recommended?.realEstatePct ?? 0)}%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* ────────────────────────────────────────────────────────── */}
              {/* TAB 3: SUBSCRIPTION CULL LIST & NEGOTIATIONS */}
              {/* ────────────────────────────────────────────────────────── */}
              {activeTab === "CULLS" && (
                <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                  {/* Hero Savings Banner */}
                  <div
                    style={{
                      background: "#FFF1F2",
                      border: "2px solid #E11D48",
                      boxShadow: "3px 3px 0 #E11D48",
                      padding: "16px 20px",
                      borderRadius: "3px",
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      flexWrap: "wrap",
                      gap: "12px",
                    }}
                  >
                    <div>
                      <div style={{ fontFamily: "var(--mono)", fontSize: "10.5px", fontWeight: 900, color: "#9F1239" }}>
                        ✂️ RECURRING SUBSCRIPTION ELIMINATION TARGET
                      </div>
                      <div style={{ fontFamily: "var(--display)", fontSize: "24px", fontWeight: 900, color: "#BE123C" }}>
                        +{formatCurrency(totalAnnualCullSavings, 0, currency)}/year in Recaptured Free Cash
                      </div>
                    </div>
                    <span
                      style={{
                        fontFamily: "var(--mono)",
                        fontSize: "11px",
                        fontWeight: 900,
                        background: "#E11D48",
                        color: "#FFFFFF",
                        padding: "4px 10px",
                        borderRadius: "2px",
                      }}
                    >
                      {analysis.subscriptionCullList?.length || 0} LEAKS IDENTIFIED
                    </span>
                  </div>

                  {/* List of Culls */}
                  {analysis.subscriptionCullList && analysis.subscriptionCullList.length > 0 ? (
                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                      {analysis.subscriptionCullList.map((cull, i) => {
                        const isExpanded = expandedScriptIndex === i;

                        return (
                          <div
                            key={i}
                            style={{
                              background: "#FFFFFF",
                              border: "1.5px solid var(--ink, #0A0A0A)",
                              boxShadow: "2.5px 2.5px 0 var(--ink, #0A0A0A)",
                              borderRadius: "3px",
                              padding: "14px 16px",
                            }}
                          >
                            <div
                              style={{
                                display: "flex",
                                justifyContent: "space-between",
                                alignItems: "flex-start",
                                flexWrap: "wrap",
                                gap: "10px",
                              }}
                            >
                              <div>
                                <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                                  <b style={{ fontFamily: "var(--display)", fontSize: "16px" }}>
                                    {cull.name}
                                  </b>
                                  {cull.actionType && (
                                    <span
                                      style={{
                                        fontFamily: "var(--mono)",
                                        fontSize: "9.5px",
                                        fontWeight: 900,
                                        background:
                                          cull.actionType === "CANCEL"
                                            ? "#FEE2E2"
                                            : cull.actionType === "RENEGOTIATE"
                                            ? "#FEF3C7"
                                            : "#E0F2FE",
                                        color:
                                          cull.actionType === "CANCEL"
                                            ? "#991B1B"
                                            : cull.actionType === "RENEGOTIATE"
                                            ? "#92400E"
                                            : "#0369A1",
                                        padding: "1px 6px",
                                        borderRadius: "2px",
                                        border: "1px solid currentColor",
                                      }}
                                    >
                                      {cull.actionType}
                                    </span>
                                  )}
                                  <span
                                    style={{
                                      fontFamily: "var(--mono)",
                                      fontSize: "9.5px",
                                      fontWeight: 800,
                                      color: cull.severity === "HIGH" ? "#DC2626" : "#4B5563",
                                    }}
                                  >
                                    [{cull.severity} PRIORITY]
                                  </span>
                                </div>

                                <div
                                  style={{
                                    fontFamily: "var(--mono)",
                                    fontSize: "11px",
                                    color: "#555555",
                                    marginTop: "4px",
                                  }}
                                >
                                  {cull.reason}
                                </div>
                              </div>

                              <div style={{ textAlign: "right" }}>
                                <div
                                  style={{
                                    fontFamily: "var(--display)",
                                    fontSize: "18px",
                                    fontWeight: 900,
                                    color: "#16A34A",
                                  }}
                                >
                                  +{formatCurrency(cull.annualSavings, 0, currency)}/yr
                                </div>
                              </div>
                            </div>

                            {/* Optional Negotiation Script */}
                            {cull.negotiationScript && (
                              <div style={{ marginTop: "10px" }}>
                                <button
                                  type="button"
                                  onClick={() =>
                                    setExpandedScriptIndex(isExpanded ? null : i)
                                  }
                                  style={{
                                    background: "transparent",
                                    border: "none",
                                    fontFamily: "var(--mono)",
                                    fontSize: "10.5px",
                                    fontWeight: 800,
                                    color: "#0369A1",
                                    cursor: "pointer",
                                    display: "flex",
                                    alignItems: "center",
                                    gap: "4px",
                                    padding: "0",
                                  }}
                                >
                                  <MessageSquareQuote size={12} />
                                  {isExpanded ? "Hide Negotiation Script" : "Show Copy-Paste Negotiation Script"}
                                  {isExpanded ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
                                </button>

                                {isExpanded && (
                                  <div
                                    style={{
                                      background: "#F0F9FF",
                                      border: "1px solid #0284C7",
                                      padding: "8px 12px",
                                      borderRadius: "2px",
                                      marginTop: "6px",
                                      fontFamily: "var(--mono)",
                                      fontSize: "11px",
                                      color: "#075985",
                                      position: "relative",
                                    }}
                                  >
                                    “{cull.negotiationScript}”
                                    <button
                                      type="button"
                                      onClick={() => {
                                        navigator.clipboard.writeText(cull.negotiationScript!);
                                        playSound.click();
                                      }}
                                      style={{
                                        display: "block",
                                        marginTop: "4px",
                                        fontSize: "9.5px",
                                        fontFamily: "var(--mono)",
                                        fontWeight: 800,
                                        background: "#0284C7",
                                        color: "#FFFFFF",
                                        border: "none",
                                        padding: "2px 6px",
                                        borderRadius: "2px",
                                        cursor: "pointer",
                                      }}
                                    >
                                      📋 Copy Script
                                    </button>
                                  </div>
                                )}
                              </div>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  ) : (
                    <div
                      style={{
                        padding: "30px",
                        textAlign: "center",
                        fontFamily: "var(--mono)",
                        fontSize: "12px",
                        color: "#16A34A",
                        background: "#DCFCE7",
                        border: "1.5px solid #16A34A",
                        borderRadius: "3px",
                      }}
                    >
                      🎉 Zero wasteful subscriptions identified. Your recurring burn is highly optimized!
                    </div>
                  )}
                </div>
              )}

              {/* ────────────────────────────────────────────────────────── */}
              {/* TAB 4: DEBT ACCELERATION & SIP WEALTH ROADMAP */}
              {/* ────────────────────────────────────────────────────────── */}
              {activeTab === "DEBT_SIP" && (
                <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
                  {/* Debt Strategy Box */}
                  {analysis.debtAccelerationStrategy && (
                    <div
                      style={{
                        background: "#FFFFFF",
                        border: "2px solid var(--ink, #0A0A0A)",
                        boxShadow: "3.5px 3.5px 0 var(--ink, #0A0A0A)",
                        padding: "18px 20px",
                        borderRadius: "3px",
                      }}
                    >
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "space-between",
                          alignItems: "center",
                          marginBottom: "8px",
                          flexWrap: "wrap",
                          gap: "8px",
                        }}
                      >
                        <div
                          style={{
                            fontFamily: "var(--mono)",
                            fontSize: "10.5px",
                            fontWeight: 900,
                            color: "#166534",
                            textTransform: "uppercase",
                            letterSpacing: "0.06em",
                            display: "flex",
                            alignItems: "center",
                            gap: "5px",
                          }}
                        >
                          <Target size={13} aria-hidden="true" />
                          RECOMMENDED DEBT KNOCKOUT ROUTE: {analysis.debtAccelerationStrategy.recommendedStrategy}
                        </div>
                        <span
                          style={{
                            fontFamily: "var(--mono)",
                            fontSize: "10px",
                            fontWeight: 900,
                            background: "#DCFCE7",
                            color: "#166534",
                            border: "1px solid #16A34A",
                            padding: "2px 8px",
                            borderRadius: "2px",
                          }}
                        >
                          Saves {formatCurrency(analysis.debtAccelerationStrategy.projectedInterestSavings, 0, currency)} Interest
                        </span>
                      </div>

                      <p
                        style={{
                          fontFamily: "var(--sans)",
                          fontSize: "13.5px",
                          color: "#0A0A0A",
                          lineHeight: 1.45,
                          marginBottom: "12px",
                        }}
                      >
                        {analysis.debtAccelerationStrategy.strategyRationale}
                      </p>

                      <div
                        style={{
                          background: "#F0FDF4",
                          border: "1.5px solid #16A34A",
                          padding: "12px 14px",
                          borderRadius: "2px",
                          display: "flex",
                          justifyContent: "space-between",
                          alignItems: "center",
                          flexWrap: "wrap",
                          gap: "10px",
                          fontFamily: "var(--mono)",
                          fontSize: "11.5px",
                        }}
                      >
                        <div>
                          Priority Target:{" "}
                          <b style={{ color: "#15803D" }}>
                            {analysis.debtAccelerationStrategy.targetPriorityDebt}
                          </b>
                        </div>
                        <div style={{ color: "#166534", fontWeight: 800 }}>
                          Recommended Extra: +{formatCurrency(analysis.debtAccelerationStrategy.extraPaymentRecommendation, 0, currency)}/mo
                        </div>
                      </div>
                    </div>
                  )}

                  {/* SIP & Recurring Wealth Strategy Box */}
                  {analysis.investmentStrategy ? (
                    <div
                      style={{
                        background: "#FFFFFF",
                        border: "2px solid var(--ink, #0A0A0A)",
                        boxShadow: "3.5px 3.5px 0 var(--ink, #0A0A0A)",
                        padding: "18px 20px",
                        borderRadius: "3px",
                      }}
                    >
                      <div
                        style={{
                          fontFamily: "var(--mono)",
                          fontSize: "10.5px",
                          fontWeight: 900,
                          color: "#D97706",
                          textTransform: "uppercase",
                          letterSpacing: "0.06em",
                          marginBottom: "8px",
                          display: "flex",
                          alignItems: "center",
                          gap: "5px",
                        }}
                      >
                        <Coins size={13} aria-hidden="true" />
                        SYSTEMATIC WEALTH COMPOUNDING (SIP / DCA ROADMAP)
                      </div>

                      <div
                        style={{
                          display: "grid",
                          gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
                          gap: "10px",
                          marginBottom: "12px",
                        }}
                      >
                        <div style={{ background: "#FEF3C7", padding: "10px 12px", borderRadius: "2px", border: "1px solid #D97706" }}>
                          <div style={{ fontFamily: "var(--mono)", fontSize: "9.5px", fontWeight: 900, color: "#92400E" }}>
                            CURRENT MONTHLY SIP
                          </div>
                          <div style={{ fontFamily: "var(--display)", fontSize: "18px", fontWeight: 900, color: "#78350F" }}>
                            {formatCurrency(analysis.investmentStrategy.currentMonthlySIP, 0, currency)}/mo
                          </div>
                        </div>

                        <div style={{ background: "#DCFCE7", padding: "10px 12px", borderRadius: "2px", border: "1px solid #16A34A" }}>
                          <div style={{ fontFamily: "var(--mono)", fontSize: "9.5px", fontWeight: 900, color: "#166534" }}>
                            SUGGESTED TARGET SIP
                          </div>
                          <div style={{ fontFamily: "var(--display)", fontSize: "18px", fontWeight: 900, color: "#14532D" }}>
                            {formatCurrency(analysis.investmentStrategy.suggestedMonthlySIP, 0, currency)}/mo
                          </div>
                        </div>

                        <div style={{ background: "#0A0A0A", color: "#FFE600", padding: "10px 12px", borderRadius: "2px" }}>
                          <div style={{ fontFamily: "var(--mono)", fontSize: "9.5px", fontWeight: 900, color: "#A3A3A3" }}>
                            10-YEAR COMPOUND POOL
                          </div>
                          <div style={{ fontFamily: "var(--display)", fontSize: "18px", fontWeight: 900, color: "#FFE600" }}>
                            +{formatCurrency(analysis.investmentStrategy.tenYearCompoundingImpact, 0, currency)}
                          </div>
                        </div>
                      </div>

                      <p style={{ fontFamily: "var(--mono)", fontSize: "11px", color: "#444444", lineHeight: 1.4, margin: "0 0 10px 0" }}>
                        💡 <b>Diversification Guidance:</b> {analysis.investmentStrategy.assetDiversificationTip}
                      </p>

                      {/* Suggested Allocations */}
                      {analysis.investmentStrategy.suggestedAllocations && Array.isArray(analysis.investmentStrategy.suggestedAllocations) && (
                        <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                          {analysis.investmentStrategy.suggestedAllocations.map((alloc, idx) => (
                            <div
                              key={idx}
                              style={{
                                display: "flex",
                                justifyContent: "space-between",
                                alignItems: "center",
                                background: "#F8FAFC",
                                border: "1px solid #CBD5E1",
                                padding: "8px 12px",
                                borderRadius: "2px",
                                fontFamily: "var(--mono)",
                                fontSize: "11px",
                              }}
                            >
                              <span>
                                <b>{alloc?.assetType || "Asset"}</b> ({alloc?.percentage ?? 50}% allocation) — <span style={{ color: "#666" }}>{alloc?.rationale || "Growth"}</span>
                              </span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  ) : null}
                </div>
              )}

              {/* ────────────────────────────────────────────────────────── */}
              {/* TAB 5: TACTICAL ACTION CHECKLIST */}
              {/* ────────────────────────────────────────────────────────── */}
              {activeTab === "CHECKLIST" && (
                <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                  <div
                    style={{
                      fontFamily: "var(--mono)",
                      fontSize: "11px",
                      fontWeight: 900,
                      textTransform: "uppercase",
                      color: "#444444",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "space-between",
                    }}
                  >
                    <span>⚡ STEP-BY-STEP EXECUTION GAMEPLAN</span>
                    <span style={{ color: "#16A34A" }}>
                      {Object.values(completedTaskIds).filter(Boolean).length} /{" "}
                      {analysis.tacticalPlan?.length || analysis.cashFlowOptimization?.length || 0} Completed
                    </span>
                  </div>

                  {/* Tactical Plan list */}
                  {analysis.tacticalPlan && analysis.tacticalPlan.length > 0 ? (
                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                      {analysis.tacticalPlan.map((task, i) => {
                        const taskId = `task-${i}`;
                        const isDone = Boolean(completedTaskIds[taskId]);

                        return (
                          <div
                            key={i}
                            onClick={() => toggleTask(taskId)}
                            style={{
                              background: isDone ? "#F0FDF4" : "#FFFFFF",
                              border: `1.5px solid ${isDone ? "#16A34A" : "var(--ink, #0A0A0A)"}`,
                              boxShadow: isDone ? "none" : "2.5px 2.5px 0 var(--ink, #0A0A0A)",
                              padding: "14px 16px",
                              borderRadius: "3px",
                              cursor: "pointer",
                              display: "flex",
                              gap: "12px",
                              alignItems: "flex-start",
                              opacity: isDone ? 0.7 : 1,
                              transition: "all 0.15s ease",
                            }}
                          >
                            <input
                              type="checkbox"
                              checked={isDone}
                              onChange={() => {}} // Handled by parent container click
                              style={{ marginTop: "3px", cursor: "pointer", width: "16px", height: "16px", accentColor: "#16A34A" }}
                            />
                            <div style={{ flex: 1 }}>
                              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "3px", flexWrap: "wrap", gap: "6px" }}>
                                <b
                                  style={{
                                    fontFamily: "var(--display)",
                                    fontSize: "14.5px",
                                    textDecoration: isDone ? "line-through" : "none",
                                  }}
                                >
                                  {task.title}
                                </b>
                                <div style={{ display: "flex", gap: "6px", alignItems: "center" }}>
                                  <span
                                    style={{
                                      fontFamily: "var(--mono)",
                                      fontSize: "9px",
                                      fontWeight: 900,
                                      background: task.phase === "IMMEDIATE_7_DAYS" ? "#FEE2E2" : task.phase === "NEXT_30_DAYS" ? "#FEF3C7" : "#E0F2FE",
                                      color: task.phase === "IMMEDIATE_7_DAYS" ? "#991B1B" : task.phase === "NEXT_30_DAYS" ? "#92400E" : "#0369A1",
                                      padding: "1px 6px",
                                      borderRadius: "2px",
                                    }}
                                  >
                                    {task.phase === "IMMEDIATE_7_DAYS" ? "7 DAYS" : task.phase === "NEXT_30_DAYS" ? "30 DAYS" : "90 DAYS"}
                                  </span>
                                  <span
                                    style={{
                                      fontFamily: "var(--mono)",
                                      fontSize: "9.5px",
                                      fontWeight: 900,
                                      color: "#16A34A",
                                    }}
                                  >
                                    {task.impact}
                                  </span>
                                </div>
                              </div>
                              <div style={{ fontFamily: "var(--mono)", fontSize: "11px", color: "#555555" }}>
                                {task.action}
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  ) : analysis.cashFlowOptimization && analysis.cashFlowOptimization.length > 0 ? (
                    /* Fallback for older audits */
                    <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                      {analysis.cashFlowOptimization.map((act, i) => (
                        <div
                          key={i}
                          style={{
                            background: "#FFFFFF",
                            border: "1.5px solid var(--ink, #0A0A0A)",
                            padding: "12px 14px",
                            borderRadius: "3px",
                          }}
                        >
                          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "2px" }}>
                            <b style={{ fontFamily: "var(--display)", fontSize: "14px" }}>{act.title}</b>
                            <span style={{ fontFamily: "var(--mono)", fontSize: "10px", fontWeight: 800, color: "#16A34A" }}>
                              {act.impact}
                            </span>
                          </div>
                          <div style={{ fontFamily: "var(--mono)", fontSize: "11px", color: "#555555" }}>
                            {act.action}
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : null}
                </div>
              )}

              {/* ── MODAL FOOTER ── */}
              <div
                className="ledger-modal-footer"
                style={{
                  marginTop: "8px",
                  paddingTop: "14px",
                  borderTop: "1.5px solid #0A0A0A",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  flexWrap: "wrap",
                  gap: "10px",
                }}
              >
                <button
                  type="button"
                  disabled={loading}
                  className="btn-ledger btn-ledger-ai"
                  onClick={handleRunAudit}
                  style={{ fontSize: "11px" }}
                >
                  <RotateCcw size={12} aria-hidden="true" />
                  {loading ? "✨ RE-AUDITING..." : "✨ RE-RUN AUDIT"}
                </button>

                <div style={{ display: "flex", gap: "8px" }}>
                  <button
                    type="button"
                    className="btn-ledger"
                    onClick={handleCopyExecutiveBrief}
                    style={{ fontSize: "11px" }}
                  >
                    {copiedBrief ? "✓ COPIED" : "📋 COPY REPORT"}
                  </button>
                  <button
                    type="button"
                    className="btn-ledger btn-ledger-primary"
                    onClick={onClose}
                    style={{ fontSize: "11px" }}
                  >
                    DONE / CLOSE
                  </button>
                </div>
              </div>
            </div>
            </LedgerErrorBoundary>
          ) : null}
        </div>
      </div>
    </div>
  );
};
