import { generateObject } from "ai";
import { z } from "zod";
import { NextRequest, NextResponse } from "next/server";
import { requireUserId, AuthError } from "@/lib/session";
import { languageModel, gatewayProviderOptions, gatewayErrorMessage } from "@/lib/ai/models";
import {
  getUserSubscriptions,
  getUserDebts,
  getUserAssets,
  getUserIncomes,
  getUserInvestments,
  createFinancialAudit,
} from "@/lib/dal/ledger";
import { calculateSubscriptionMetrics } from "@/lib/ledger/subscriptionMetrics";
import { calculateInvestmentMetrics } from "@/lib/ledger/investmentMetrics";
import { calculateCashFlow } from "@/lib/ledger/cashFlow";
import { calculateDebtPayoff } from "@/lib/ledger/debtPayoff";
import { getCurrencySymbol } from "@/lib/ledger/formatters";

const AUDIT_MODEL = "google/gemini-3.5-flash";

const PillarSchema = z.object({
  name: z.string().describe("Human-readable name of the financial pillar"),
  score: z.number().min(0).max(100).describe("Pillar rating from 0 to 100"),
  grade: z.enum(["A+", "A", "B", "C", "D", "F"]).describe("Letter grade"),
  verdict: z.string().describe("1-2 sentence specific audit finding for this pillar"),
  status: z.enum(["EXCELLENT", "STABLE", "WARNING", "CRITICAL"]).describe("Health status tag"),
});

const AuditSchema = z.object({
  healthScore: z.number().min(0).max(100).describe("Overall composite financial velocity health score from 0 to 100"),
  summaryVerdict: z.string().describe("Sharp, 2-3 sentence executive verdict summarizing financial velocity, risk exposure, burn drag, and 10-year compounding momentum"),
  currency: z.string().default("USD").describe("The dominant ISO currency code (e.g. INR, USD, EUR)"),
  pillars: z.object({
    runway: PillarSchema.describe("Emergency Cash & Liquidity Reserves Pillar"),
    debt: PillarSchema.describe("Debt Leverage, APR Exposure & Payoff Velocity Pillar"),
    burn: PillarSchema.describe("Fixed Subscription & Recurring Burn Efficiency Pillar"),
    wealth: PillarSchema.describe("Systematic Wealth Building & SIP Investment Velocity Pillar"),
  }),
  projections: z.array(
    z.object({
      year: z.number().describe("Milestone year horizon: 1, 3, 5, or 10"),
      statusQuoNetWorth: z.number().describe("Projected net worth if current habits continue unchanged"),
      optimizedNetWorth: z.number().describe("Projected net worth if AI audit recommendations (culling waste, debt acceleration, SIP boosting) are implemented"),
      deltaGain: z.number().describe("Total additional wealth generated by executing the audit recommendations"),
    })
  ).describe("Comparative 10-year Net Worth Trajectory Modeling (Status Quo vs AI Optimized)"),
  subscriptionCullList: z.array(
    z.object({
      name: z.string().describe("Name of the subscription or recurring service"),
      category: z.string().optional().describe("Category of the subscription"),
      currentCost: z.number().optional().describe("Current monthly or annual cost"),
      cadence: z.string().optional().describe("Cadence e.g. MONTHLY, YEARLY"),
      annualSavings: z.number().describe("Estimated annual savings if eliminated or downgraded"),
      actionType: z.enum(["CANCEL", "DOWNGRADE", "RENEGOTIATE", "SWITCH_ANNUAL"]).default("CANCEL").describe("Specific action recommended"),
      reason: z.string().describe("Specific mathematical or usage rationale for culling or modifying this charge"),
      negotiationScript: z.string().optional().describe("Exact 1-2 sentence negotiation or retention script the user can copy-paste to customer support"),
      severity: z.enum(["HIGH", "MEDIUM", "LOW"]),
    })
  ).describe("Prioritized list of subscriptions to cancel, pause, or renegotiate"),
  debtAccelerationStrategy: z.object({
    recommendedStrategy: z.enum(["AVALANCHE", "SNOWBALL"]).describe("Optimal debt payoff algorithm"),
    strategyRationale: z.string().describe("Mathematical or psychological justification for the chosen strategy"),
    targetPriorityDebt: z.string().describe("The exact name of the specific debt account to eliminate first"),
    extraPaymentRecommendation: z.number().describe("Recommended additional monthly surplus payment toward the priority debt"),
    projectedInterestSavings: z.number().describe("Projected total lifetime interest saved by following the acceleration route"),
    payoffMonthsSaved: z.number().optional().describe("Number of months knocked off debt payoff timeline"),
    estimatedDebtFreeDate: z.string().optional().describe("Estimated month & year of total debt freedom e.g. 'Oct 2027'"),
  }),
  investmentStrategy: z.object({
    currentMonthlySIP: z.number().describe("Current monthly recurring investment allocation"),
    suggestedMonthlySIP: z.number().describe("Recommended target monthly recurring investment allocation after redirecting freed cash flow"),
    suggestedAllocations: z.array(
      z.object({
        assetType: z.string().describe("Target asset e.g. Nifty 50 / S&P 500 Index, Digital Gold, Mutual Funds, Retirement"),
        percentage: z.number().describe("Suggested percentage allocation of total monthly investment pool (sum to 100)"),
        rationale: z.string().describe("Why this asset allocation fits their risk and timeline"),
      })
    ),
    assetDiversificationTip: z.string().describe("Key strategic advice for portfolio diversification and risk mitigation"),
    tenYearCompoundingImpact: z.number().describe("Total projected 10-year wealth generated by the suggested monthly investment rate"),
  }).describe("Systematic Wealth Building & DCA / SIP Roadmap"),
  assetAllocation: z.object({
    current: z.object({
      liquidCashPct: z.number().describe("% in liquid checking / savings"),
      equitiesAndMutualFundsPct: z.number().describe("% in stocks, ETFs, mutual funds"),
      preciousMetalsPct: z.number().describe("% in Gold / Silver"),
      cryptoPct: z.number().describe("% in Crypto"),
      realEstatePct: z.number().describe("% in Real Estate"),
      retirementPct: z.number().describe("% in Tax-advantaged retirement accounts"),
      otherPct: z.number().describe("% in other assets"),
    }),
    recommended: z.object({
      liquidCashPct: z.number().describe("Target % in liquid checking / savings"),
      equitiesAndMutualFundsPct: z.number().describe("Target % in stocks, ETFs, mutual funds"),
      preciousMetalsPct: z.number().describe("Target % in Gold / Silver"),
      cryptoPct: z.number().describe("Target % in Crypto"),
      realEstatePct: z.number().describe("Target % in Real Estate"),
      retirementPct: z.number().describe("Target % in Tax-advantaged retirement accounts"),
      otherPct: z.number().describe("Target % in other assets"),
    }),
    rebalanceAdvice: z.string().describe("Specific tactical advice on rebalancing current portfolio allocation"),
  }).describe("Asset Allocation Balance Sheet Breakdown"),
  cashFlowOptimization: z.array(
    z.object({
      title: z.string(),
      impact: z.string().describe("Quantified impact (e.g. '+₹12,000/yr', '+$250/mo free surplus')"),
      action: z.string().describe("Concrete, high-leverage move to execute"),
    })
  ).describe("Top tactical cash flow optimizations"),
  tacticalPlan: z.array(
    z.object({
      phase: z.enum(["IMMEDIATE_7_DAYS", "NEXT_30_DAYS", "LONG_TERM_90_DAYS"]).describe("Time horizon"),
      title: z.string().describe("Short action headline"),
      impact: z.string().describe("Financial gain or risk reduction metric"),
      action: z.string().describe("Detailed step-by-step instructions"),
      priority: z.enum(["URGENT", "RECOMMENDED", "OPPORTUNITY"]).describe("Execution priority"),
    })
  ).describe("Prioritized step-by-step action checklist"),
  runwayAnalysis: z.object({
    currentRunwayMonths: z.number().describe("Liquid runway in months"),
    safetyEvaluation: z.enum(["CRITICAL", "LEAN", "HEALTHY", "FORTRESS"]),
    targetEmergencyFund: z.number().describe("Target emergency fund amount in user's currency based on 3-6 months of fixed burn"),
  }),
});

const AUDIT_SYSTEM = `You are a Senior Quantitative Wealth Architect, Institutional Portfolio Strategist, and Frugal Chief Financial Officer.
Your tone is archival, direct, incisive, mathematically exact, and deeply empowering.
You do not give generic advice like "save more money" or "cut dining out".
Instead, you analyze the user's REAL ledger data: their exact recurring subscriptions, debt APRs, monthly cash flow surplus/deficit, emergency liquid runway, and recurring wealth investments (SIPs/DCA into Gold, Stocks, Mutual Funds, Crypto, Retirement, etc.).

Key Mathematical Principles:
1. PREDATORY INTEREST ELIMINATION: Debts with >15% APR are critical fiscal emergencies. Recommend mathematically rigorous Avalanche or Snowball prioritization.
2. RECURRING BURN CULLING: Subscriptions represent continuous wealth drain. Calculate exact annual and 10-year compounding losses.
3. WEALTH VELOCITY & COMPOUNDING: Redirecting culled subscription waste and extra surplus into recurring investments (SIPs) at 8-14% CAGR creates massive asymmetric 10-year wealth gains.
4. RUNWAY PRESERVATION: Ensure an emergency liquid cash fortress of 3 to 6 months of fixed outflows before aggressive illiquid investments.
5. DOMINANT CURRENCY INTEGRITY: Maintain exact numerical values in the user's dominant currency (INR, USD, EUR, etc.) as provided in the balance sheet.`;

export async function POST(req: NextRequest) {
  try {
    const userId = await requireUserId(req);

    const [subscriptions, debts, assets, incomes, investments] = await Promise.all([
      getUserSubscriptions(userId),
      getUserDebts(userId),
      getUserAssets(userId),
      getUserIncomes(userId),
      getUserInvestments(userId).catch(() => []),
    ]);

    const subMetrics = calculateSubscriptionMetrics(subscriptions);
    const invMetrics = calculateInvestmentMetrics(investments);
    const { cashFlow, netWorth } = calculateCashFlow(
      incomes,
      subscriptions,
      debts,
      assets,
      investments
    );
    const avalanche = calculateDebtPayoff(debts, "AVALANCHE", 100);
    const snowball = calculateDebtPayoff(debts, "SNOWBALL", 100);

    // Determine dominant currency across ledger records
    const currencyCounts: Record<string, number> = {};
    [...subscriptions, ...investments, ...incomes, ...assets].forEach((item: any) => {
      const c = item.currency || "USD";
      currencyCounts[c] = (currencyCounts[c] || 0) + 1;
    });
    const dominantCurrency =
      Object.entries(currencyCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || "USD";
    const sym = getCurrencySymbol(dominantCurrency);

    const prompt = `
# COMPREHENSIVE FINANCIAL BALANCE SHEET FOR AUDIT:
Currency: ${dominantCurrency} (${sym})

## 1. Cash Flow & Burn Velocity:
- Gross Monthly Inflow: ${sym}${cashFlow.monthlyGrossIncome.toFixed(2)}
- Estimated Monthly Tax Withholding: ${sym}${cashFlow.monthlyTaxWithholding.toFixed(2)}
- Net Monthly Take-Home: ${sym}${cashFlow.monthlyNetTakeHome.toFixed(2)}
- Fixed Monthly Subscriptions Burn: ${sym}${cashFlow.monthlySubscriptions.toFixed(2)} (${subMetrics.activeCount} active items)
- Fixed Monthly Debt Minimum Payments: ${sym}${cashFlow.monthlyDebtMinimums.toFixed(2)}
- Recurring Wealth Investments (SIPs/DCA): ${sym}${cashFlow.monthlyRecurringInvestments.toFixed(2)}
- Total Fixed Outflow: ${sym}${cashFlow.totalFixedOutflow.toFixed(2)}
- Net Free Monthly Surplus: ${sym}${cashFlow.monthlyNetSurplus.toFixed(2)}
- Savings Rate: ${cashFlow.savingsRatePct}%
- Wealth Velocity Rate (% of net income deployed to investments + surplus): ${cashFlow.wealthVelocityPct}%
- Liquid Emergency Cash: ${sym}${cashFlow.liquidCashTotal.toFixed(2)}
- Liquid Runway: ${cashFlow.runwayMonths.toFixed(1)} months

## 2. Balance Sheet & Net Worth:
- Total Assets: ${sym}${netWorth.totalAssets.toFixed(2)}
  - Liquid Cash & HYSA: ${sym}${netWorth.totalLiquidCash.toFixed(2)}
  - Public Investments & Equities: ${sym}${netWorth.totalInvestments.toFixed(2)}
  - Tax-Advantaged Retirement: ${sym}${netWorth.totalRetirement.toFixed(2)}
  - Real Estate: ${sym}${netWorth.totalRealEstate.toFixed(2)}
  - Crypto Holdings: ${sym}${netWorth.totalCrypto.toFixed(2)}
  - Other Tangible Assets: ${sym}${netWorth.totalOtherAssets.toFixed(2)}
- Total Liabilities (Debt): ${sym}${netWorth.totalLiabilities.toFixed(2)}
- Total Net Worth: ${sym}${netWorth.netWorth.toFixed(2)}
- Debt-to-Asset Ratio: ${netWorth.debtToAssetRatioPct}%

## 3. Recurring Wealth Investments (SIPs / DCA commitments) (${investments.length} active positions):
${investments
  .map(
    (inv) =>
      `- "${inv.name}" [${inv.assetType}]: ${sym}${inv.amount}/${inv.cadence.toLowerCase()} via ${
        inv.platform || "Direct"
      } (Expected CAGR: ${inv.expectedReturnRate ?? 10}%, Status: ${inv.status}, Current Holding: ${sym}${
        inv.currentValuation || 0
      })`
  )
  .join("\n") || "No recurring investments recorded."}
- Total Monthly Investment Deployed: ${sym}${invMetrics.monthlyTotal.toFixed(2)}/mo (${sym}${invMetrics.yearlyTotal.toFixed(2)}/yr)
- Weighted Average Portfolio Expected CAGR: ${invMetrics.weightedReturnRatePct}%

## 4. Itemized Subscriptions & Recurring Charges (${subscriptions.length} items, Total: ${sym}${subMetrics.monthlyTotal.toFixed(2)}/mo):
${subscriptions
  .map(
    (s) =>
      `- "${s.name}" [${s.category}]: ${sym}${s.amount} (${s.cadence}), Status: ${s.status}${
        s.trialEndsDate ? `, Trial Ends: ${s.trialEndsDate}` : ""
      }${s.notes ? `, Notes: "${s.notes}"` : ""}`
  )
  .join("\n") || "No subscriptions recorded."}

## 5. Liabilities & Debt Accounts (${debts.length} accounts, Total Debt: ${sym}${netWorth.totalLiabilities.toFixed(2)}):
${debts
  .map(
    (d) =>
      `- "${d.name}" [${d.debtType}]: Balance: ${sym}${d.balance}, APR: ${d.interestRate}%, Min Payment: ${sym}${d.minPayment}/mo${
        d.targetPayment ? `, Target: ${sym}${d.targetPayment}/mo` : ""
      }${d.isPaidOff ? " [PAID OFF]" : ""}`
  )
  .join("\n") || "Debt-free! Zero liabilities recorded."}

## Payoff Model Computations:
- Avalanche Route (Highest APR first): ${avalanche.monthsToPayoff} months to debt freedom, Total Interest: ${sym}${avalanche.totalInterestPaid.toFixed(2)}
- Snowball Route (Lowest Balance first): ${snowball.monthsToPayoff} months to debt freedom, Total Interest: ${sym}${snowball.totalInterestPaid.toFixed(2)}

# INSTRUCTIONS:
1. Conduct a deep, incisive, non-generic quantitative audit.
2. Formulate 4 Pillar Scores (0-100) with letter grades (A+, A, B, C, D, F) and statuses (EXCELLENT, STABLE, WARNING, CRITICAL).
3. Compute exact 10-year comparative wealth trajectories (Status Quo vs Optimized at Years 1, 3, 5, and 10) incorporating culled subscription cash flow redirected into recurring investment compounding.
4. Provide concrete subscription culls with custom negotiation scripts and severity tags.
5. Deliver a prioritized action plan grouped by Immediate (7 Days), 30 Days, and 90 Days.
6. Ensure all output values are formulated in ${dominantCurrency}.
`;

    const result = await generateObject({
      model: languageModel(AUDIT_MODEL),
      system: AUDIT_SYSTEM,
      prompt,
      schema: AuditSchema,
      providerOptions: {
        ...gatewayProviderOptions(AUDIT_MODEL, ["feature:financial-ledger-audit"]),
      },
    });

    const savedAudit = await createFinancialAudit({
      userId,
      analysis: result.object as any,
    });

    return NextResponse.json({ audit: savedAudit });
  } catch (error) {
    if (error instanceof AuthError) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const message = gatewayErrorMessage(error);
    console.error("Error generating financial audit:", error);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
